version: "3.9"

services:
  postgres:
    container_name: beavr-db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=beavr
      - POSTGRES_USER=beavr
      - POSTGRES_DB=beavr

volumes:
  postgres_data:
